# Generated by Django 5.1.6 on 2026-03-07 22:56

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('markdown', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='0.1.0', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('agent_type', models.CharField(choices=[('CODER', 'Coder'), ('REVIEWER', 'Reviewer'), ('TESTER', 'Tester'), ('PLANNER', 'Planner'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('encrypted_configuration', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('is_external', models.BooleanField(default=False)),
                ('external_command', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'sub_agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubAgentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_config', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_agent_skills',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='0.1.0', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('markdown', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('CODING', 'Coding'), ('TESTING', 'Testing'), ('REVIEW', 'Review'), ('DOCUMENTATION', 'Documentation'), ('DEPLOYMENT', 'Deployment'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('input_schema', models.JSONField(blank=True, null=True)),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('compatible_agent_types', models.JSONField(blank=True, default=list)),
                ('is_external', models.BooleanField(default=False)),
                ('external_command', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizations.organization')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('changelog', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_versions', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.skill')),
            ],
            options={
                'db_table': 'skill_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
