# Generated by Django 5.1.6 on 2026-03-01 21:38

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_integrationconfig_repositorycredential"),
        ("projects", "0004_projectsettings_repository_credential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.CharField(default="0.1.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("CODER", "Coder"),
                            ("REVIEWER", "Reviewer"),
                            ("TESTER", "Tester"),
                            ("PLANNER", "Planner"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("capabilities", models.JSONField(blank=True, default=list)),
                (
                    "encrypted_configuration",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                ("max_concurrent_tasks", models.IntegerField(default=1)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "assigned_projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_agents",
                        to="projects.project",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "agents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.CharField(default="0.1.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CODING", "Coding"),
                            ("TESTING", "Testing"),
                            ("REVIEW", "Review"),
                            ("DOCUMENTATION", "Documentation"),
                            ("DEPLOYMENT", "Deployment"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("input_schema", models.JSONField(blank=True, null=True)),
                ("output_schema", models.JSONField(blank=True, null=True)),
                ("compatible_agent_types", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("custom_config", models.JSONField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_skills",
                        to="agents.agent",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_skills",
                        to="agents.skill",
                    ),
                ),
            ],
            options={
                "db_table": "agent_skills",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("changelog", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_skill_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="agents.skill",
                    ),
                ),
            ],
            options={
                "db_table": "skill_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_org_agent_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_org_skill_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentskill",
            constraint=models.UniqueConstraint(
                fields=("agent", "skill"), name="unique_agent_skill"
            ),
        ),
    ]
