# Generated by Django 5.1.6 on 2026-03-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agent_unique_org_agent_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='content',
            new_name='markdown',
        ),
    ]
