# Generated by Django 5.1.6 on 2026-03-04 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agentskill_agent_remove_agentskill_skill_and_more'),
        ('organizations', '0002_integrationconfig_repositorycredential'),
        ('projects', '0008_alter_issue_labels_delete_label_delete_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagent',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_sub_agents', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='subagent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subagent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_agents', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subagentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agent_skills', to='agents.skill'),
        ),
        migrations.AlterField(
            model_name='subagentskill',
            name='sub_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agent_skills', to='agents.subagent'),
        ),
    ]
