# Generated by Django 5.1.6 on 2026-03-07 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
            ],
            options={
                'db_table': 'cycles',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('field_changed', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'issue_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('artifact_type', models.CharField(choices=[('PLAN', 'Plan'), ('DESIGN_DOC', 'Design Doc'), ('TECHNICAL_SPEC', 'Technical Spec'), ('TEST_PLAN', 'Test Plan'), ('OTHER', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('session_id', models.CharField(max_length=255)),
                ('requires_approval', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'issue_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='issue_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'issue_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('short_summary', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='BACKLOG', max_length=20)),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='NONE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('REVIEWER', 'Reviewer')], default='CONTRIBUTOR', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('WEBPAGE', 'Webpage')], max_length=20)),
            ],
            options={
                'db_table': 'project_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_url', models.URLField(blank=True, default='')),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('branch_naming_convention', models.CharField(blank=True, default='', max_length=255)),
                ('required_reviewers_count', models.IntegerField(default=1)),
                ('auto_close_completed_issues', models.BooleanField(default=False)),
                ('issue_prefix', models.CharField(max_length=10)),
                ('estimation_method', models.CharField(choices=[('STORY_POINTS', 'Story Points'), ('T_SHIRT', 'T-Shirt'), ('HOURS', 'Hours')], default='STORY_POINTS', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'project settings',
                'db_table': 'project_settings',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='BACKLOG', max_length=20)),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='NONE', max_length=20)),
                ('estimate', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('external_tracker_name', models.CharField(blank=True, default='', max_length=100)),
                ('external_tracker_url', models.URLField(blank=True, default='')),
                ('external_tracker_id', models.CharField(blank=True, default='', max_length=255)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.cycle')),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
