# Generated by Django 5.1.6 on 2026-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='auto_task_prompt_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
