# Generated by Django 5.1.6 on 2026-03-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectsettings_auto_task_prompt_template'),
        ('toony_agents', '0003_agentsystemevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueartifact',
            name='agent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='toony_agents.agenttask'),
        ),
        migrations.AlterField(
            model_name='issueartifact',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
