# Generated by Django 5.1.6 on 2026-03-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_make_artifact_agent_task_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='auto_close_completed_issues',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='estimation_method',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='required_reviewers_count',
        ),
    ]
