# Generated by Django 5.1.6 on 2026-03-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_unused_settings_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='estimate',
        ),
    ]
