# Generated by Django 5.1.6 on 2026-03-27 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_issue_estimate_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFileTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree', models.JSONField(default=list)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('synced_at', models.DateTimeField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_tree', to='projects.project')),
            ],
            options={
                'db_table': 'project_file_trees',
            },
        ),
    ]
