# Generated by Django 5.1.6 on 2026-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfiletree'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiletree',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
