# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        # Remove the issue FK
        migrations.RemoveField(
            model_name="workflow",
            name="issue",
        ),
        # Remove the label FK
        migrations.RemoveField(
            model_name="workflow",
            name="label",
        ),
        # Add M2M labels
        migrations.AddField(
            model_name="workflow",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflows",
                to="workspace.label",
            ),
        ),
        # Update unique_global_workflow_slug constraint
        migrations.RemoveConstraint(
            model_name="workflow",
            name="unique_global_workflow_slug",
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization__isnull", True),
                    ("project__isnull", True),
                ),
                fields=("slug",),
                name="unique_global_workflow_slug",
            ),
        ),
    ]
