# Generated by Django 5.1.6 on 2026-03-01 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_integrationconfig_repositorycredential'),
        ('projects', '0003_issue_comment_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='repository_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='organizations.repositorycredential'),
        ),
    ]
