# Generated by Django 5.1.6 on 2026-03-01 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_integrationconfig_repositorycredential'),
        ('projects', '0004_projectsettings_repository_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='issues_project_6804e7_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'created_at'], name='issues_project_0b4a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'sort_order', '-created_at'], name='issues_project_35fc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organization', 'name'], name='teams_organiz_a96817_idx'),
        ),
    ]
