# Generated by Django 5.1.6 on 2026-03-02 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_issue_issues_project_6804e7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('WEBPAGE', 'Webpage')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
            options={
                'db_table': 'project_resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
