# Generated by Django 5.1.6 on 2026-03-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_short_summary_projectresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
    ]
