# Generated by Django 5.1.6 on 2026-03-06 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_issue_prefix_override_to_issue_prefix'),
        ('toony_agents', '0004_add_project_to_agent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('artifact_type', models.CharField(choices=[('PLAN', 'Plan'), ('DESIGN_DOC', 'Design Doc'), ('TECHNICAL_SPEC', 'Technical Spec'), ('TEST_PLAN', 'Test Plan'), ('OTHER', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('session_id', models.CharField(max_length=255)),
                ('requires_approval', models.BooleanField(default=False)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='toony_agents.agenttask')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.issue')),
            ],
            options={
                'db_table': 'issue_artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
