# Generated by Django 5.1.6 on 2026-03-01 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, default='', upload_to='org_logos/')),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_project_methodology', models.CharField(choices=[('SCRUM', 'Scrum'), ('KANBAN', 'Kanban'), ('CUSTOM', 'Custom')], default='SCRUM', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('allowed_ip_ranges', models.JSONField(blank=True, null=True)),
                ('audit_log_retention_days', models.IntegerField(default=90)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'organization settings',
                'db_table': 'organization_settings',
            },
        ),
    ]
