# Generated by Django 5.1.6 on 2026-03-01 21:28

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('LINEAR', 'Linear'), ('JIRA', 'Jira'), ('TRELLO', 'Trello'), ('SLACK', 'Slack'), ('CUSTOM', 'Custom')], max_length=20)),
                ('encrypted_credentials', encrypted_model_fields.fields.EncryptedTextField()),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='organizations.organization')),
            ],
            options={
                'db_table': 'integration_configs',
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider'), name='unique_org_integration_provider')],
            },
        ),
        migrations.CreateModel(
            name='RepositoryCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('BITBUCKET', 'Bitbucket'), ('CUSTOM', 'Custom')], max_length=20)),
                ('credential_type', models.CharField(choices=[('TOKEN', 'Token'), ('SSH_KEY', 'SSH Key'), ('APP_CREDENTIAL', 'App Credential')], max_length=20)),
                ('encrypted_value', encrypted_model_fields.fields.EncryptedTextField()),
                ('url_pattern', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_credentials', to='organizations.organization')),
            ],
            options={
                'db_table': 'repository_credentials',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_credential_name')],
            },
        ),
    ]
