# Generated by Django 5.1.6 on 2026-03-11 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subagent',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_sub_agents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='subagent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subagent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_agents', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subagentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agent_skills', to='agents.skill'),
        ),
        migrations.AddField(
            model_name='subagentskill',
            name='sub_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agent_skills', to='agents.subagent'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'slug'), name='unique_org_skill_slug'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_skill_slug'),
        ),
        migrations.AddConstraint(
            model_name='subagent',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'slug'), name='unique_org_sub_agent_slug'),
        ),
        migrations.AddConstraint(
            model_name='subagent',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_sub_agent_slug'),
        ),
        migrations.AddConstraint(
            model_name='subagentskill',
            constraint=models.UniqueConstraint(fields=('sub_agent', 'skill'), name='unique_sub_agent_skill'),
        ),
    ]
