# Generated by Django 5.1.6 on 2026-03-11 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('RUNNING', 'Running'), ('WAITING_FOR_ANSWER', 'Waiting for Answer'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agent_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='projects.project')),
            ],
            options={
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTaskQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.UUIDField(unique=True)),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='toony_agents.agenttask')),
            ],
            options={
                'db_table': 'agent_task_questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToonyAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('BUSY', 'Busy')], default='OFFLINE', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organizations', models.ManyToManyField(blank=True, related_name='toony_agents', to='organizations.organization')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_toony_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toony_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='toony_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='toony_agents.toonyagent'),
        ),
        migrations.CreateModel(
            name='ToonyAgentKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('key_prefix', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_toony_agent_keys', to=settings.AUTH_USER_MODEL)),
                ('toony_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='toony_agents.toonyagent')),
            ],
            options={
                'db_table': 'toony_agent_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOG', 'Log'), ('TOOL_USE', 'Tool Use'), ('TOOL_RESULT', 'Tool Result'), ('QUESTION_ASKED', 'Question Asked'), ('QUESTION_ANSWERED', 'Question Answered'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ERROR', 'Error')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='toony_agents.agenttask')),
            ],
            options={
                'db_table': 'task_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'sequence'], name='task_events_task_id_d3aaaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['toony_agent', 'status'], name='agent_tasks_toony_a_7ff0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['organization', 'status'], name='agent_tasks_organiz_100add_idx'),
        ),
    ]
