# Generated by Django 5.1.6 on 2026-03-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('toony_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='projects.issue'),
        ),
    ]
