# Generated by Django 5.1.6 on 2026-03-13 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0003_projectsettings_auto_task_prompt_template'),
        ('toony_agents', '0002_agenttask_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REPO_CLONE_SUCCESS', 'Repo Clone Success'), ('REPO_CLONE_ERROR', 'Repo Clone Error'), ('CONFIG_SYNC_COMPLETED', 'Config Sync Completed'), ('CONFIG_SYNC_FAILED', 'Config Sync Failed')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('toony_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='toony_agents.toonyagent')),
            ],
            options={
                'db_table': 'agent_system_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['toony_agent', '-created_at'], name='agent_syste_toony_a_26bdac_idx')],
            },
        ),
    ]
