# Generated by Django 5.1.6 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toony_agents', '0003_agentsystemevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('QUEUED', 'Queued'),
                    ('PAUSED', 'Paused'),
                    ('ASSIGNED', 'Assigned'),
                    ('RUNNING', 'Running'),
                    ('WAITING_FOR_ANSWER', 'Waiting for Answer'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='QUEUED',
                max_length=20,
            ),
        ),
    ]
