# Generated by Django 5.1.6 on 2026-03-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toony_agents', '0004_alter_agenttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('LOG', 'Log'), ('TOOL_USE', 'Tool Use'), ('TOOL_RESULT', 'Tool Result'), ('QUESTION_ASKED', 'Question Asked'), ('QUESTION_ANSWERED', 'Question Answered'), ('TOOL_APPROVAL', 'Tool Approval'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
