# Generated by Django 5.1.6 on 2026-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toony_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('LOG', 'Log'), ('TOOL_USE', 'Tool Use'), ('TOOL_RESULT', 'Tool Result'), ('APPROVAL_NEEDED', 'Approval Needed'), ('APPROVAL_RESPONSE', 'Approval Response'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
