# Generated by Django 5.1.6 on 2026-03-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_integrationconfig_repositorycredential'),
        ('toony_agents', '0002_add_session_id_to_agent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='organizations.organization'),
        ),
    ]
