# Generated by Django 5.1.6 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
