# Generated by Django 5.1.6 on 2026-03-01 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_integrationconfig_repositorycredential"),
        ("projects", "0004_projectsettings_repository_credential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("LINEAR", "Linear"),
                            ("JIRA", "Jira"),
                            ("TRELLO", "Trello"),
                            ("ASANA", "Asana"),
                            ("GITHUB_PROJECTS", "GitHub Projects"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIALLY_COMPLETED", "Partially Completed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("progress", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                ("imported_items", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("external_type", models.CharField(max_length=100)),
                ("internal_id", models.UUIDField(default=uuid.uuid4)),
                ("internal_type", models.CharField(max_length=100)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="importers.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "import_mappings",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("import_job", "external_id", "external_type"),
                        name="unique_import_mapping",
                    )
                ],
            },
        ),
    ]
