# Generated by Django 5.1.6 on 2026-03-01 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0001_initial'),
        ('organizations', '0002_integrationconfig_repositorycredential'),
        ('projects', '0004_projectsettings_repository_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['organization', '-created_at'], name='import_jobs_organiz_bb7eee_idx'),
        ),
    ]
