# Generated by Django 5.1.6 on 2026-03-11 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='importers.importjob'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['organization', '-created_at'], name='import_jobs_organiz_bb7eee_idx'),
        ),
        migrations.AddConstraint(
            model_name='importmapping',
            constraint=models.UniqueConstraint(fields=('import_job', 'external_id', 'external_type'), name='unique_import_mapping'),
        ),
    ]
