# Generated by Django 5.1.6 on 2026-03-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='allowed_ip_ranges',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='audit_log_retention_days',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='default_project_methodology',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='timezone',
        ),
    ]
