# Generated by Django 5.1.6 on 2026-03-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_unused_settings_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationSettings',
        ),
    ]
